apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  api_url: http://192.168.43.223:5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: darbi/stage_front:latest   # Mettez à jour l'image Docker
          imagePullPolicy: Always  # Vous pouvez également mettre à jour la politique de récupération
          env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: api_url
          ports:
          - containerPort: 80 


---

apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # Port on the pods
  type: LoadBalancer
# Remplacez cette adresse IP par votre adresse IP publique


